- hosts: localhost
  gather_facts: yes
  vars:
    rst_ansible_project_files_dir: '{{ansible_env.HOME}}/code/note2/rst/ansible/ansible_project/files/cqh_file_watcher'
  tasks:
    - debug:
        var: ansible_env
    - name: create directory
      file: 
        path: '{{item}}'
        state: directory
        owner: '{{ansible_env.USER}}'
        group: '{{ansible_env.USER}}'
      with_items:
        - '{{rst_ansible_project_files_dir}}'
        - '{{rst_ansible_project_files_dir}}/playbooks'
    - name: copy template files
      copy:
        src: '{{proj_dir}}/{{item}}'
        dest: '{{rst_ansible_project_files_dir}}/{{item}}'
      with_items:
        - 'setup.py'
        - 'tasks.py'
    - name: sync files
      synchronize:
        src: '{{proj_dir}}/playbooks'
        dest: '{{rst_ansible_project_files_dir}}/'