- hosts: localhost
  tasks:
    - name: create directory
      file: 
        path: '/etc/cqh_file_watcher.d'
        state: directory
        mode: 0777
      become: yes
      become_method: sudo
    - name: copy file_watcher conf
      template:
        src: '{{item.src}}'
        dest: '{{item.dest}}'
      with_items:
        - {"src": "{{proj_dir}}/playbooks/conf/file_watcher.json.j2", "dest": "/etc/cqh_file_watcher.d/{{proj_name}}.json"}
        - {"src": "{{proj_dir}}/playbooks/conf/file_watcher_lint.json.j2", "dest": "/etc/cqh_file_watcher.d/lint_{{proj_name}}.json"}
      become: yes
      become_method: sudo

    - name: copy mock supervisor template for centos
      template:
        src: '{{proj_dir}}/playbooks/conf/file_watcher_{{proj_name}}.conf.j2'
        dest: '/etc/supervisord.d/file_watcher_{{proj_name}}.ini'
      become: yes
      become_method: sudo
      when:
        - ansible_os_family == "RedHat"
    - name: restart mock supervisor
      supervisorctl:
        name: '{{item}}'
        state: 'restarted'
      with_items:
        - 'file_watcher_{{proj_name}}'
        - 'file_watcher_lint_{{proj_name}}'
      become: yes
      become_method: sudo
